# Generalized Linear Regression

## This is Multiple Linear Regression on diabetes dataset (CampusX)

## Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dataset

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
data = load_diabetes()

In [4]:
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [5]:
data['data']

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
data['feature_names']

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [7]:
df = pd.DataFrame(data = data['data'], columns = data['feature_names'])

In [8]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [9]:
data['target']

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [10]:
df['target'] = data['target']

In [11]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

## Adding x0 = 1 as column

In [12]:
df = df.reset_index()
df

index       age       sex       bmi        bp        s1        s2  \
0        0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821   
1        1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163   
2        2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194   
3        3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991   
4        4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596   
..     ...       ...       ...       ...       ...       ...       ...   
437    437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566   
438    438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165   
439    439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840   
440    440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283   
441    441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809   

           s3        s4        s5        s6  target  
0   -0.043401 -0.002592  0.019907 -0.017646   151.0  
1    0.074412 -0.039493 -0.068332 -0.092204    75.0  
2   -0.032356 -0.002592  0.002861 -0.025930   141.0  
3   -0.036038  0.034309  0.022688 -0.009362   206.0  
4    0.008142 -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...       ...     ...  
437 -0.028674 -0.002592  0.031193  0.007207   178.0  
438 -0.028674  0.034309 -0.018114  0.044485   104.0  
439 -0.024993 -0.011080 -0.046883  0.015491   132.0  
440 -0.028674  0.026560  0.044529 -0.025930   220.0  
441  0.173816 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 12 columns]

In [13]:
cols = df.columns
cols
cols = list(cols) # cause index doesn't accept change

In [14]:
cols

['index',
 'age',
 'sex',
 'bmi',
 'bp',
 's1',
 's2',
 's3',
 's4',
 's5',
 's6',
 'target']

In [15]:
cols[0] = 'x0'
cols

['x0', 'age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6', 'target']

In [16]:
df.columns = cols
df

x0       age       sex       bmi        bp        s1        s2  \
0      0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821   
1      1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163   
2      2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194   
3      3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991   
4      4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596   
..   ...       ...       ...       ...       ...       ...       ...   
437  437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566   
438  438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165   
439  439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840   
440  440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283   
441  441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809   

           s3        s4        s5        s6  target  
0   -0.043401 -0.002592  0.019907 -0.017646   151.0  
1    0.074412 -0.039493 -0.068332 -0.092204    75.0  
2   -0.032356 -0.002592  0.002861 -0.025930   141.0  
3   -0.036038  0.034309  0.022688 -0.009362   206.0  
4    0.008142 -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...       ...     ...  
437 -0.028674 -0.002592  0.031193  0.007207   178.0  
438 -0.028674  0.034309 -0.018114  0.044485   104.0  
439 -0.024993 -0.011080 -0.046883  0.015491   132.0  
440 -0.028674  0.026560  0.044529 -0.025930   220.0  
441  0.173816 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 12 columns]

In [17]:
df['x0'] = 1
df

x0       age       sex       bmi        bp        s1        s2        s3  \
0     1  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1     1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2     1  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3     1 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4     1  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..   ..       ...       ...       ...       ...       ...       ...       ...   
437   1  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438   1 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439   1  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440   1 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441   1 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 12 columns]

## Train Test Split

In [18]:
l = [1,2,3,4,5]
print(l[:-1])
print(l[-1:])
print(l[-1])

[1, 2, 3, 4]
[5]
5


In [20]:
# x = df['TV']
# x

In [21]:
# x.ndim

#### Here the dimension of x is 1 which will cause error in train test split ,since tran test split expects x to be 2 dimensional.

#### so the way we can do is 
#### i)  x = np.array(df['TV']).reshape(len(x),1)
#### ii) x = df[['TV']]
#### ii) x = df[df.columns[:-1]] 

In [22]:
# x = np.array(df['TV']).reshape(len(x),1)
# x
# x.ndim

In [23]:
# x = df[['TV']]
# x
# x.ndim

In [24]:
x = df[df.columns[:-1]]
x

x0       age       sex       bmi        bp        s1        s2        s3  \
0     1  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1     1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2     1  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3     1 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4     1  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..   ..       ...       ...       ...       ...       ...       ...       ...   
437   1  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438   1 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439   1  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440   1 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441   1 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 11 columns]

In [25]:
x.ndim

2

In [26]:
y = df[df.columns[-1:]]
y

target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

In [27]:
y.ndim

2

In [28]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [29]:
x_train

x0       age       sex       bmi        bp        s1        s2        s3  \
70    1 -0.001882 -0.044642 -0.069797 -0.012556 -0.000193 -0.009143  0.070730   
37    1 -0.009147 -0.044642  0.011039 -0.057313 -0.024960 -0.042963  0.030232   
170   1  0.023546  0.050680 -0.020218 -0.036656 -0.013953 -0.015092  0.059685   
400   1 -0.023677 -0.044642  0.045529  0.090729 -0.018080 -0.035447  0.070730   
286   1 -0.038207 -0.044642 -0.054707 -0.077970 -0.033216 -0.086490  0.140681   
..   ..       ...       ...       ...       ...       ...       ...       ...   
299   1  0.038076  0.050680 -0.013751 -0.015999 -0.035968 -0.021982 -0.013948   
22    1 -0.085430 -0.044642 -0.004050 -0.009113 -0.002945  0.007767  0.022869   
72    1  0.063504  0.050680 -0.004050 -0.012556  0.103003  0.048790  0.056003   
15    1 -0.052738  0.050680 -0.018062  0.080401  0.089244  0.107662 -0.039719   
168   1  0.001751  0.050680  0.059541 -0.002228  0.061725  0.063195 -0.058127   

           s4        s5        s6  
70  -0.039493 -0.062917  0.040343  
37  -0.039493  0.017036 -0.005220  
170 -0.039493 -0.096435 -0.017646  
400 -0.039493 -0.034522 -0.009362  
286 -0.076395 -0.019198 -0.005220  
..        ...       ...       ...  
299 -0.002592 -0.025953 -0.001078  
22  -0.039493 -0.061176 -0.013504  
72  -0.002592  0.084492 -0.017646  
15   0.108111  0.036060 -0.042499  
168  0.108111  0.068986  0.127328  

[353 rows x 11 columns]

In [30]:
# x_train = x_train.reset_index()
# x_train

In [31]:
y_train

target
70     48.0
37    276.0
170    47.0
400   175.0
286    60.0
..      ...
299    83.0
22     68.0
72    202.0
15    171.0
168   268.0

[353 rows x 1 columns]

# Linear Regression

In [32]:
np.array(x_train)

array([[ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [ 1.        , -0.00914709, -0.04464164, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 1.        ,  0.02354575,  0.05068012, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 1.        ,  0.06350368,  0.05068012, ..., -0.00259226,
         0.08449153, -0.01764613],
       [ 1.        , -0.05273755,  0.05068012, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 1.        ,  0.00175052,  0.05068012, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [33]:
X = np.array(x_train)
X

array([[ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [ 1.        , -0.00914709, -0.04464164, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 1.        ,  0.02354575,  0.05068012, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 1.        ,  0.06350368,  0.05068012, ..., -0.00259226,
         0.08449153, -0.01764613],
       [ 1.        , -0.05273755,  0.05068012, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 1.        ,  0.00175052,  0.05068012, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [34]:
np.transpose(X)

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-0.00188202, -0.00914709,  0.02354575, ...,  0.06350368,
        -0.05273755,  0.00175052],
       [-0.04464164, -0.04464164,  0.05068012, ...,  0.05068012,
         0.05068012,  0.05068012],
       ...,
       [-0.03949338, -0.03949338, -0.03949338, ..., -0.00259226,
         0.1081111 ,  0.1081111 ],
       [-0.06291688,  0.01703607, -0.09643495, ...,  0.08449153,
         0.03606033,  0.06898589],
       [ 0.04034337, -0.0052198 , -0.01764613, ..., -0.01764613,
        -0.04249877,  0.12732762]])

In [35]:
Xt = np.transpose(X)
Xt

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-0.00188202, -0.00914709,  0.02354575, ...,  0.06350368,
        -0.05273755,  0.00175052],
       [-0.04464164, -0.04464164,  0.05068012, ...,  0.05068012,
         0.05068012,  0.05068012],
       ...,
       [-0.03949338, -0.03949338, -0.03949338, ..., -0.00259226,
         0.1081111 ,  0.1081111 ],
       [-0.06291688,  0.01703607, -0.09643495, ...,  0.08449153,
         0.03606033,  0.06898589],
       [ 0.04034337, -0.0052198 , -0.01764613, ..., -0.01764613,
        -0.04249877,  0.12732762]])

In [36]:
XtX = np.dot(Xt,X)
XtX

array([[ 3.53000000e+02, -3.59226823e-02, -5.07016847e-01,
        -7.22721765e-01, -1.21931294e-01, -3.39194171e-01,
        -7.01634988e-01,  8.14279161e-01, -9.51231584e-01,
        -1.03738610e-01, -3.39006149e-01],
       [-3.59226823e-02,  8.20967496e-01,  1.41874960e-01,
         1.80487652e-01,  2.83447221e-01,  2.35892391e-01,
         1.90418063e-01, -6.31103606e-02,  1.84124182e-01,
         2.54930348e-01,  2.86247901e-01],
       [-5.07016847e-01,  1.41874960e-01,  7.95580922e-01,
         7.04549395e-02,  1.79747998e-01,  2.63140905e-04,
         8.60276097e-02, -2.99960819e-01,  2.57031428e-01,
         1.08678991e-01,  1.87427433e-01],
       [-7.22721765e-01,  1.80487652e-01,  7.04549395e-02,
         7.92372628e-01,  3.35896866e-01,  1.99230748e-01,
         2.15252524e-01, -2.94169684e-01,  3.22034052e-01,
         3.59480196e-01,  3.15896870e-01],
       [-1.21931294e-01,  2.83447221e-01,  1.79747998e-01,
         3.35896866e-01,  8.00195622e-01,  1.98146915e-01,
  

In [37]:
XtXinverse = np.linalg.inv(XtX)
XtXinverse

array([[ 2.85058113e-03, -3.80221852e-04,  7.47474697e-04,
         2.53023091e-03, -5.43099025e-04,  4.28745325e-04,
        -7.58817849e-04,  4.15683642e-04,  5.51327024e-03,
        -3.64032607e-03, -4.10173799e-05],
       [-3.80221852e-04,  1.56256338e+00, -1.65221785e-01,
        -4.22134896e-03, -3.02050400e-01, -1.91042687e-02,
        -1.81335783e-01, -1.64258266e-01,  7.11951450e-02,
        -2.62414202e-01, -3.16337562e-01],
       [ 7.47474697e-04, -1.65221785e-01,  1.64517233e+00,
         2.72282619e-01, -3.15128257e-01,  7.91472682e-01,
        -3.49865857e-01,  5.50207453e-03, -7.10933011e-01,
         5.04207258e-02, -2.06987698e-01],
       [ 2.53023091e-03, -4.22134896e-03,  2.72282619e-01,
         2.00512084e+00, -5.25944627e-01,  1.38390412e+00,
        -1.37471764e+00,  1.74658427e-02,  9.39446076e-02,
        -9.06361438e-01, -3.41358502e-01],
       [-5.43099025e-04, -3.02050400e-01, -3.15128257e-01,
        -5.25944627e-01,  1.81641420e+00, -3.93342350e-01,
  

In [38]:
b = np.dot(XtXinverse,Xt)
b

array([[ 2.69404681e-03,  2.63467433e-03,  3.01258469e-03, ...,
         2.57016324e-03,  3.22572297e-03,  3.33369916e-03],
       [-8.77989356e-04,  7.63814849e-03,  6.04712641e-02, ...,
         5.74961412e-02, -1.18393786e-01, -5.93720472e-02],
       [-6.74431099e-02, -2.46589028e-02,  1.07714242e-01, ...,
         1.51004994e-01,  2.90874485e-02,  2.74369926e-02],
       ...,
       [ 1.60987064e-01, -2.21785273e-02,  9.39557437e-02, ...,
        -3.44502755e-01,  3.68611267e-01,  3.19167550e-01],
       [-1.90052947e-01,  2.33378820e-01, -5.11591216e-01, ...,
        -1.02322508e-02,  1.01998817e-01, -4.32516983e-02],
       [ 1.38707908e-01,  1.79627760e-02, -3.11850643e-04, ...,
        -9.16949298e-02, -1.31036281e-01,  1.64914689e-01]])

In [39]:
np.array(y_train)

array([[ 48.],
       [276.],
       [ 47.],
       [175.],
       [ 60.],
       [ 81.],
       [242.],
       [197.],
       [137.],
       [129.],
       [138.],
       [160.],
       [116.],
       [101.],
       [147.],
       [100.],
       [144.],
       [ 69.],
       [219.],
       [107.],
       [168.],
       [236.],
       [109.],
       [321.],
       [128.],
       [ 43.],
       [ 72.],
       [ 55.],
       [141.],
       [283.],
       [ 59.],
       [150.],
       [346.],
       [124.],
       [186.],
       [308.],
       [272.],
       [190.],
       [ 63.],
       [ 91.],
       [ 72.],
       [ 65.],
       [158.],
       [ 90.],
       [185.],
       [ 45.],
       [199.],
       [206.],
       [ 61.],
       [139.],
       [296.],
       [281.],
       [122.],
       [ 95.],
       [ 40.],
       [127.],
       [145.],
       [108.],
       [185.],
       [ 53.],
       [132.],
       [101.],
       [263.],
       [ 94.],
       [295.],
       [259.],
       [23

In [40]:
Y = np.array(y_train)
Y

array([[ 48.],
       [276.],
       [ 47.],
       [175.],
       [ 60.],
       [ 81.],
       [242.],
       [197.],
       [137.],
       [129.],
       [138.],
       [160.],
       [116.],
       [101.],
       [147.],
       [100.],
       [144.],
       [ 69.],
       [219.],
       [107.],
       [168.],
       [236.],
       [109.],
       [321.],
       [128.],
       [ 43.],
       [ 72.],
       [ 55.],
       [141.],
       [283.],
       [ 59.],
       [150.],
       [346.],
       [124.],
       [186.],
       [308.],
       [272.],
       [190.],
       [ 63.],
       [ 91.],
       [ 72.],
       [ 65.],
       [158.],
       [ 90.],
       [185.],
       [ 45.],
       [199.],
       [206.],
       [ 61.],
       [139.],
       [296.],
       [281.],
       [122.],
       [ 95.],
       [ 40.],
       [127.],
       [145.],
       [108.],
       [185.],
       [ 53.],
       [132.],
       [101.],
       [263.],
       [ 94.],
       [295.],
       [259.],
       [23

In [41]:
b = np.dot(b,Y)
b

array([[ 151.88331005],
       [  -9.15865318],
       [-205.45432163],
       [ 516.69374454],
       [ 340.61999905],
       [-895.5520019 ],
       [ 561.22067904],
       [ 153.89310954],
       [ 126.73139688],
       [ 861.12700152],
       [  52.42112238]])

In [42]:
b.shape

(11, 1)

In [43]:
b.ndim

2

In [44]:
n = len(x_train.columns)
n

11

In [45]:
print('intercept :',b[0,0])

intercept : 151.8833100525417


In [46]:
print('coefficients :')
for i in range(1,n):
    print('b'+str(i),':',b[i,0])

coefficients :
b1 : -9.158653181170266
b2 : -205.45432163451972
b3 : 516.6937445408257
b4 : 340.61999904554864
b5 : -895.5520019034723
b6 : 561.2206790412974
b7 : 153.89310953636254
b8 : 126.73139687846668
b9 : 861.1270015229954
b10 : 52.42112237904715


In [47]:
b

array([[ 151.88331005],
       [  -9.15865318],
       [-205.45432163],
       [ 516.69374454],
       [ 340.61999905],
       [-895.5520019 ],
       [ 561.22067904],
       [ 153.89310954],
       [ 126.73139688],
       [ 861.12700152],
       [  52.42112238]])

In [48]:
x_test

x0       age       sex       bmi        bp        s1        s2        s3  \
212   1  0.067136 -0.044642  0.003494  0.035644  0.049341  0.031254  0.070730   
422   1 -0.078165  0.050680  0.077863  0.052858  0.078236  0.064447  0.026550   
67    1  0.041708  0.050680 -0.014828 -0.017135 -0.005697  0.008394 -0.013948   
89    1 -0.045472 -0.044642 -0.048241 -0.019442 -0.000193 -0.016032  0.067048   
390   1  0.009016  0.050680  0.069241  0.059744  0.017694 -0.023234 -0.047082   
..   ..       ...       ...       ...       ...       ...       ...       ...   
129   1  0.009016 -0.044642  0.016428  0.004658  0.009439  0.010586 -0.028674   
417   1 -0.052738 -0.044642  0.071397 -0.074527 -0.015328 -0.001314  0.004460   
332   1  0.030811 -0.044642  0.104809  0.076958 -0.011201 -0.011335 -0.058127   
150   1  0.023546 -0.044642  0.070319  0.025315 -0.034592 -0.014466 -0.032356   
192   1  0.056239  0.050680 -0.030996  0.008101  0.019070  0.021233  0.033914   

           s4        s5        s6  
212 -0.039493 -0.000612  0.019633  
422 -0.002592  0.040673 -0.009362  
67  -0.001854 -0.011897  0.003064  
89  -0.039493 -0.024795  0.019633  
390  0.034309  0.103297  0.073480  
..        ...       ...       ...  
129  0.034309  0.038968  0.119043  
417 -0.021412 -0.046883  0.003064  
332  0.034309  0.057108  0.036201  
150 -0.002592 -0.019198 -0.009362  
192 -0.039493 -0.029526 -0.059067  

[89 rows x 11 columns]

In [49]:
y_test

target
212    73.0
422   233.0
67     97.0
89    111.0
390   277.0
..      ...
129   268.0
417    55.0
332   270.0
150   288.0
192    91.0

[89 rows x 1 columns]

In [50]:
# y_prediction

y_cap = list()
y_prediction = 0

for row in x_test.index:
    for i in range(len(x_test.columns)):
        y_prediction = y_prediction + b[i,0] * x_test[x_test.columns[i]][row]
    
    y_cap.append(y_prediction)
    y_prediction = 0

y_cap

[154.12138809538388,
 204.81835117652113,
 124.93755352869645,
 106.08950892826081,
 258.5348575985561,
 256.3310074008204,
 118.75087616091729,
 119.52440696107092,
 101.50816734991433,
 190.54048660815045,
 141.70656811061923,
 172.51883961465617,
 174.33861648821446,
 134.809427061262,
 294.1399453657878,
 94.11798038458302,
 211.9705979485928,
 156.49579378119395,
 134.21000428481727,
 119.62664644088285,
 148.87842251198666,
 165.00873409287837,
 151.10021037547727,
 176.04063756372486,
 133.27769647287911,
 221.29555392247377,
 197.17324941409592,
 96.15776879970186,
 50.26012710959056,
 230.4858031667962,
 242.06073865938393,
 114.11129217711597,
 67.07532416760307,
 94.52943824732783,
 201.21415375235506,
 167.05136201269355,
 159.8812679972984,
 192.78746658751817,
 114.49551325245072,
 233.48234551299345,
 140.82563044691443,
 121.06804090464465,
 192.2748077151156,
 191.12738845238925,
 179.16865787866436,
 148.34935601317426,
 163.47414621761686,
 276.8164788384625,
 100.17

In [51]:
len(y_cap)

89

## Model Evaluation on Test Dataset

In [52]:
y_test

target
212    73.0
422   233.0
67     97.0
89    111.0
390   277.0
..      ...
129   268.0
417    55.0
332   270.0
150   288.0
192    91.0

[89 rows x 1 columns]

In [53]:
# R Square

y_mean = y_test[y_test.columns[0]].mean()

sum1 = 0
sum2 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

for i in y_test.index:
    diff = y_test[y_test.columns[0]][i] - y_mean
    sum2 = sum2 + (diff ** 2)

r2 = 1 - (sum1 / sum2)

print(r2)

0.43993386615689645


In [54]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_cap) # first comes actual value and then predicted value
print(r2)

0.43993386615689656


In [55]:
# MSE

sum1 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

mse = sum1 / (len(y_cap))
print(mse)

3094.456671566064


In [56]:
# RMSE

rmse = np.sqrt(mse)
rmse
print(rmse)

55.62784079546917


In [57]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_cap)
print('MSE :',mse)
rmse = np.sqrt(mse)
print('RMSE :',rmse)

MSE : 3094.456671566064
RMSE : 55.62784079546917
