# Generalized Linear Regression

## This is Single Linear Regression on placement dataset (CampusX)

## Library

In [131]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dataset

In [132]:
df = pd.read_csv('placement.csv')

In [133]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

## Adding x0 = 1 as column

In [134]:
df = df.reset_index()
df

index  cgpa  package
0        0  6.89     3.26
1        1  5.12     1.98
2        2  7.82     3.25
3        3  7.42     3.67
4        4  6.94     3.57
..     ...   ...      ...
195    195  6.93     2.46
196    196  5.89     2.57
197    197  7.21     3.24
198    198  7.63     3.96
199    199  6.22     2.33

[200 rows x 3 columns]

In [135]:
cols = df.columns
cols
cols = list(cols)

In [136]:
cols

['index', 'cgpa', 'package']

In [137]:
cols[0] = 'x0'
cols

['x0', 'cgpa', 'package']

In [138]:
df.columns = cols
df

x0  cgpa  package
0      0  6.89     3.26
1      1  5.12     1.98
2      2  7.82     3.25
3      3  7.42     3.67
4      4  6.94     3.57
..   ...   ...      ...
195  195  6.93     2.46
196  196  5.89     2.57
197  197  7.21     3.24
198  198  7.63     3.96
199  199  6.22     2.33

[200 rows x 3 columns]

In [139]:
df['x0'] = 1
df

x0  cgpa  package
0     1  6.89     3.26
1     1  5.12     1.98
2     1  7.82     3.25
3     1  7.42     3.67
4     1  6.94     3.57
..   ..   ...      ...
195   1  6.93     2.46
196   1  5.89     2.57
197   1  7.21     3.24
198   1  7.63     3.96
199   1  6.22     2.33

[200 rows x 3 columns]

## Train Test Split

In [140]:
l = [1,2,3,4,5]
print(l[:-1])
print(l[-1:])
print(l[-1])

[1, 2, 3, 4]
[5]
5


In [141]:
# x = df['TV']
# x

In [142]:
# x.ndim

#### Here the dimension of x is 1 which will cause error in train test split ,since tran test split expects x to be 2 dimensional.

#### so the way we can do is 
#### i)  x = np.array(df['TV']).reshape(len(x),1)
#### ii) x = df[['TV']]
#### ii) x = df[df.columns[:-1]] 

In [143]:
# x = np.array(df['TV']).reshape(len(x),1)
# x
# x.ndim

In [144]:
# x = df[['TV']]
# x
# x.ndim

In [145]:
x = df[df.columns[:-1]]
x

x0  cgpa
0     1  6.89
1     1  5.12
2     1  7.82
3     1  7.42
4     1  6.94
..   ..   ...
195   1  6.93
196   1  5.89
197   1  7.21
198   1  7.63
199   1  6.22

[200 rows x 2 columns]

In [146]:
x.ndim

2

In [147]:
y = df[df.columns[-1:]]
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [148]:
y.ndim

2

In [149]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [150]:
x_train

x0  cgpa
137   1  7.14
163   1  8.93
111   1  5.42
123   1  5.10
109   1  7.77
..   ..   ...
43    1  7.66
22    1  6.14
72    1  7.78
15    1  7.25
168   1  8.65

[160 rows x 2 columns]

In [151]:
# x_train = x_train.reset_index()
# x_train

In [152]:
y_train

package
137     3.13
163     3.91
111     2.25
123     2.30
109     4.06
..       ...
43      2.76
22      2.30
72      3.62
15      3.23
168     3.52

[160 rows x 1 columns]

# Linear Regression

In [153]:
np.array(x_train)

array([[1.  , 7.14],
       [1.  , 8.93],
       [1.  , 5.42],
       [1.  , 5.1 ],
       [1.  , 7.77],
       [1.  , 6.76],
       [1.  , 6.89],
       [1.  , 6.68],
       [1.  , 7.91],
       [1.  , 7.89],
       [1.  , 8.71],
       [1.  , 7.95],
       [1.  , 6.61],
       [1.  , 6.26],
       [1.  , 6.53],
       [1.  , 6.42],
       [1.  , 5.11],
       [1.  , 6.09],
       [1.  , 6.93],
       [1.  , 7.04],
       [1.  , 5.94],
       [1.  , 6.05],
       [1.  , 5.83],
       [1.  , 5.95],
       [1.  , 9.31],
       [1.  , 5.58],
       [1.  , 7.88],
       [1.  , 6.13],
       [1.  , 7.76],
       [1.  , 4.85],
       [1.  , 6.19],
       [1.  , 8.6 ],
       [1.  , 6.07],
       [1.  , 7.18],
       [1.  , 5.12],
       [1.  , 7.39],
       [1.  , 8.25],
       [1.  , 8.28],
       [1.  , 7.13],
       [1.  , 7.35],
       [1.  , 5.66],
       [1.  , 5.99],
       [1.  , 8.01],
       [1.  , 7.14],
       [1.  , 6.34],
       [1.  , 6.89],
       [1.  , 5.42],
       [1.  ,

In [154]:
X = np.array(x_train)
X

array([[1.  , 7.14],
       [1.  , 8.93],
       [1.  , 5.42],
       [1.  , 5.1 ],
       [1.  , 7.77],
       [1.  , 6.76],
       [1.  , 6.89],
       [1.  , 6.68],
       [1.  , 7.91],
       [1.  , 7.89],
       [1.  , 8.71],
       [1.  , 7.95],
       [1.  , 6.61],
       [1.  , 6.26],
       [1.  , 6.53],
       [1.  , 6.42],
       [1.  , 5.11],
       [1.  , 6.09],
       [1.  , 6.93],
       [1.  , 7.04],
       [1.  , 5.94],
       [1.  , 6.05],
       [1.  , 5.83],
       [1.  , 5.95],
       [1.  , 9.31],
       [1.  , 5.58],
       [1.  , 7.88],
       [1.  , 6.13],
       [1.  , 7.76],
       [1.  , 4.85],
       [1.  , 6.19],
       [1.  , 8.6 ],
       [1.  , 6.07],
       [1.  , 7.18],
       [1.  , 5.12],
       [1.  , 7.39],
       [1.  , 8.25],
       [1.  , 8.28],
       [1.  , 7.13],
       [1.  , 7.35],
       [1.  , 5.66],
       [1.  , 5.99],
       [1.  , 8.01],
       [1.  , 7.14],
       [1.  , 6.34],
       [1.  , 6.89],
       [1.  , 5.42],
       [1.  ,

In [155]:
np.transpose(X)

array([[1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 

In [156]:
Xt = np.transpose(X)
Xt

array([[1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 

In [157]:
XtX = np.dot(Xt,X)
XtX

array([[ 160.    , 1118.39  ],
       [1118.39  , 7998.8607]])

In [158]:
XtXinverse = np.linalg.inv(XtX)
XtXinverse

array([[ 0.27561826, -0.03853658],
       [-0.03853658,  0.00551315]])

In [159]:
b = np.dot(XtXinverse,Xt)
b

array([[ 4.67105102e-04, -6.85133655e-02,  6.67500154e-02,
         7.90817196e-02, -2.38109376e-02,  1.51110039e-02,
         1.01012490e-02,  1.81939299e-02, -2.92060582e-02,
        -2.84353267e-02, -6.00353188e-02, -3.07475213e-02,
         2.08914902e-02,  3.43792918e-02,  2.39744163e-02,
         2.82134396e-02,  7.86963539e-02,  4.09305096e-02,
         8.55978601e-03,  4.32076268e-03,  4.67109960e-02,
         4.24719727e-02,  5.09500193e-02,  4.63256302e-02,
        -8.31572643e-02,  6.05841633e-02, -2.80499610e-02,
         3.93890466e-02, -2.34255719e-02,  8.87158636e-02,
         3.70768521e-02, -5.57962955e-02,  4.17012412e-02,
        -1.07435793e-03,  7.83109881e-02, -9.16703884e-03,
        -4.23084940e-02, -4.34645913e-02,  8.52470859e-04,
        -7.62557581e-03,  5.75012372e-02,  4.47841672e-02,
        -3.30597158e-02,  4.67105102e-04,  3.12963657e-02,
         1.01012490e-02,  6.67500154e-02,  2.62866109e-02,
        -2.07280116e-02, -9.55240459e-03, -4.92801550e-0

In [160]:
np.array(y_train)

array([[3.13],
       [3.91],
       [2.25],
       [2.3 ],
       [4.06],
       [3.18],
       [2.7 ],
       [2.49],
       [3.15],
       [2.99],
       [4.08],
       [4.14],
       [2.6 ],
       [2.44],
       [2.71],
       [2.72],
       [1.63],
       [2.31],
       [2.51],
       [3.5 ],
       [2.24],
       [2.58],
       [2.42],
       [2.54],
       [4.37],
       [2.17],
       [3.14],
       [2.19],
       [3.54],
       [1.54],
       [2.72],
       [3.98],
       [2.46],
       [3.  ],
       [1.98],
       [2.65],
       [3.75],
       [3.67],
       [2.93],
       [3.08],
       [2.21],
       [2.84],
       [3.76],
       [3.03],
       [2.09],
       [3.26],
       [2.16],
       [2.7 ],
       [3.83],
       [2.88],
       [3.16],
       [3.04],
       [3.13],
       [3.04],
       [4.6 ],
       [3.26],
       [2.85],
       [2.09],
       [3.31],
       [3.89],
       [1.87],
       [3.11],
       [2.4 ],
       [3.48],
       [3.08],
       [2.76],
       [2.

In [161]:
Y = np.array(y_train)
Y

array([[3.13],
       [3.91],
       [2.25],
       [2.3 ],
       [4.06],
       [3.18],
       [2.7 ],
       [2.49],
       [3.15],
       [2.99],
       [4.08],
       [4.14],
       [2.6 ],
       [2.44],
       [2.71],
       [2.72],
       [1.63],
       [2.31],
       [2.51],
       [3.5 ],
       [2.24],
       [2.58],
       [2.42],
       [2.54],
       [4.37],
       [2.17],
       [3.14],
       [2.19],
       [3.54],
       [1.54],
       [2.72],
       [3.98],
       [2.46],
       [3.  ],
       [1.98],
       [2.65],
       [3.75],
       [3.67],
       [2.93],
       [3.08],
       [2.21],
       [2.84],
       [3.76],
       [3.03],
       [2.09],
       [3.26],
       [2.16],
       [2.7 ],
       [3.83],
       [2.88],
       [3.16],
       [3.04],
       [3.13],
       [3.04],
       [4.6 ],
       [3.26],
       [2.85],
       [2.09],
       [3.31],
       [3.89],
       [1.87],
       [3.11],
       [2.4 ],
       [3.48],
       [3.08],
       [2.76],
       [2.

In [162]:
b = np.dot(b,Y)
b

array([[-0.89611192],
       [ 0.55795197]])

In [163]:
b.shape

(2, 1)

In [164]:
b.ndim

2

In [166]:
n = len(x_train.columns)
n

2

In [167]:
print('intercept :',b[0,0])

intercept : -0.8961119222429405


In [168]:
print('coefficients :')
for i in range(1,n):
    print('b'+str(i),':',b[i,0])

coefficients :
b1 : 0.5579519734250753


In [171]:
b

array([[-0.89611192],
       [ 0.55795197]])

In [169]:
x_test

x0  cgpa
112   1  8.58
29    1  7.15
182   1  5.88
199   1  6.22
193   1  4.57
85    1  4.79
10    1  5.32
54    1  6.86
115   1  8.35
35    1  6.87
12    1  8.94
92    1  7.90
13    1  6.93
126   1  5.91
174   1  7.32
2     1  7.82
44    1  5.09
3     1  7.42
113   1  6.94
14    1  7.73
23    1  6.19
25    1  7.28
6     1  6.73
134   1  7.20
165   1  8.21
173   1  6.75
45    1  7.87
65    1  7.60
48    1  8.63
122   1  5.12
178   1  8.15
64    1  7.36
9     1  8.31
57    1  6.60
78    1  6.59
71    1  7.47
128   1  7.93
176   1  6.29
131   1  6.37
53    1  6.47

In [170]:
y_test

package
112     4.10
29      3.49
182     2.08
199     2.33
193     1.94
85      1.48
10      1.86
54      3.09
115     4.21
35      2.87
12      3.65
92      4.00
13      2.89
126     2.60
174     2.99
2       3.25
44      1.86
3       3.67
113     2.37
14      3.42
23      2.48
25      3.65
6       2.60
134     2.83
165     4.08
173     2.56
45      3.58
65      3.81
48      4.09
122     2.01
178     3.63
64      2.92
9       3.51
57      1.94
78      2.21
71      3.34
128     3.34
176     3.23
131     2.01
53      2.61

In [172]:
# y_prediction

y_cap = list()
y_prediction = 0

for row in x_test.index:
    for i in range(len(x_test.columns)):
        y_prediction = y_prediction + b[i,0] * x_test[x_test.columns[i]][row]
    
    y_cap.append(y_prediction)
    y_prediction = 0

y_cap

[3.8911160097442052,
 3.093244687746348,
 2.3846456814965022,
 2.5743493524610277,
 1.6537285963096537,
 1.7764780304631702,
 2.0721925763784603,
 2.931438615453076,
 3.7627870558564376,
 2.937018135187327,
 4.091978720177233,
 3.5117086678151543,
 2.9704952535928313,
 2.4013842406992545,
 3.188096523228611,
 3.4670725099411484,
 1.9438636224906927,
 3.2438917205711184,
 2.976074773327082,
 3.416856832332892,
 2.557610793258276,
 3.165778444291608,
 2.8589048589078163,
 3.121142286417602,
 3.684673779576928,
 2.870063898376318,
 3.4949701086124025,
 3.344323075787632,
 3.9190136084154594,
 1.960602181693445,
 3.6511966611714235,
 3.210414602165614,
 3.7404689769194355,
 2.786371102362556,
 2.7807915826283054,
 3.2717893192423717,
 3.528447227017906,
 2.613405990600783,
 2.6580421484747894,
 2.7138373458172964]

In [173]:
len(y_cap)

40

## Model Evaluation on Test Dataset

In [174]:
y_test

package
112     4.10
29      3.49
182     2.08
199     2.33
193     1.94
85      1.48
10      1.86
54      3.09
115     4.21
35      2.87
12      3.65
92      4.00
13      2.89
126     2.60
174     2.99
2       3.25
44      1.86
3       3.67
113     2.37
14      3.42
23      2.48
25      3.65
6       2.60
134     2.83
165     4.08
173     2.56
45      3.58
65      3.81
48      4.09
122     2.01
178     3.63
64      2.92
9       3.51
57      1.94
78      2.21
71      3.34
128     3.34
176     3.23
131     2.01
53      2.61

In [175]:
# R Square

y_mean = y_test[y_test.columns[0]].mean()

sum1 = 0
sum2 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

for i in y_test.index:
    diff = y_test[y_test.columns[0]][i] - y_mean
    sum2 = sum2 + (diff ** 2)

r2 = 1 - (sum1 / sum2)

print(r2)

0.7807301475103854


In [176]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_cap) # first comes actual value and then predicted value
print(r2)

0.7807301475103854


In [177]:
# MSE

sum1 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

mse = sum1 / (len(y_cap))
print(mse)

0.12129235313495457


In [178]:
# RMSE

rmse = np.sqrt(mse)
rmse
print(rmse)

0.34827051717731516


In [179]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_cap)
print('MSE :',mse)
rmse = np.sqrt(mse)
print('RMSE :',rmse)

MSE : 0.12129235313495457
RMSE : 0.34827051717731516
