In [4]:
import pandas as pd
import numpy as np
import pandas as pd

## Dataset

In [5]:
df = pd.read_csv("placement.csv")

In [6]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

## Train Test Split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x = df[df.columns[:-1]]
x

cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [9]:
y = df[df.columns[-1:]]
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

## Linear Regression

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
model = LinearRegression()

In [14]:
model.fit(x_train, y_train)

LinearRegression()

In [15]:
model.intercept_

array([-0.89611192])

In [16]:
model.coef_

array([[0.55795197]])

In [18]:
y_pred = model.predict(x_test)

In [19]:
y_pred

array([[3.89111601],
       [3.09324469],
       [2.38464568],
       [2.57434935],
       [1.6537286 ],
       [1.77647803],
       [2.07219258],
       [2.93143862],
       [3.76278706],
       [2.93701814],
       [4.09197872],
       [3.51170867],
       [2.97049525],
       [2.40138424],
       [3.18809652],
       [3.46707251],
       [1.94386362],
       [3.24389172],
       [2.97607477],
       [3.41685683],
       [2.55761079],
       [3.16577844],
       [2.85890486],
       [3.12114229],
       [3.68467378],
       [2.8700639 ],
       [3.49497011],
       [3.34432308],
       [3.91901361],
       [1.96060218],
       [3.65119666],
       [3.2104146 ],
       [3.74046898],
       [2.7863711 ],
       [2.78079158],
       [3.27178932],
       [3.52844723],
       [2.61340599],
       [2.65804215],
       [2.71383735]])

## Model Evaluation on Test Dataset

In [20]:
from sklearn.metrics import r2_score, mean_squared_error

In [21]:
r2 = r2_score(y_test, y_pred)
r2

0.780730147510384

In [22]:
mse = mean_squared_error(y_test, y_pred)
mse

0.12129235313495527

In [23]:
rmse = np.sqrt(mse)
rmse

0.34827051717731616