# Generalized Linear Regression

## This is Single Linear Regression on placement dataset (CampusX)

## Library

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dataset

In [49]:
df = pd.read_csv('placement.csv')

In [50]:
df

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

## Train Test Split

In [51]:
l = [1,2,3,4,5]
print(l[:-1])
print(l[-1])

[1, 2, 3, 4]
5


In [52]:
# x = df['TV']
# x

In [53]:
# x.ndim

#### Here the dimension of x is 1 which will cause error in train test split ,since tran test split expects x to be 2 dimensional.

#### so the way we can do is 
#### i)  x = np.array(df['TV']).reshape(len(x),1)
#### ii) x = df[['TV']]
#### ii) x = df[df.columns[:-1]] 

In [54]:
# x = np.array(df['TV']).reshape(len(x),1)
# x
# x.ndim

In [55]:
# x = df[['TV']]
# x
# x.ndim

In [56]:
x = df[df.columns[:-1]]
x

cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [57]:
x.ndim

2

In [58]:
y = df[df.columns[-1:]]
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [59]:
y.ndim

2

In [60]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [61]:
x_train

cgpa
137  7.14
163  8.93
111  5.42
123  5.10
109  7.77
..    ...
43   7.66
22   6.14
72   7.78
15   7.25
168  8.65

[160 rows x 1 columns]

In [62]:
x_train = x_train.reset_index()
x_train

index  cgpa
0      137  7.14
1      163  8.93
2      111  5.42
3      123  5.10
4      109  7.77
..     ...   ...
155     43  7.66
156     22  6.14
157     72  7.78
158     15  7.25
159    168  8.65

[160 rows x 2 columns]

In [63]:
y_train

package
137     3.13
163     3.91
111     2.25
123     2.30
109     4.06
..       ...
43      2.76
22      2.30
72      3.62
15      3.23
168     3.52

[160 rows x 1 columns]

# Linear Regression

In [64]:
n = len(x_train.columns)
n

2

In [65]:
A = np.zeros((n,n))
A

array([[0., 0.],
       [0., 0.]])

In [66]:
H = np.zeros((n,1))
H

array([[0.],
       [0.]])

In [67]:
for i in range(n):
    for j in range(n):
        if i==0 and j==0 :
            A[i,j] = len(x_train)
        else:
            if i==0 :
                A[i,j] = x_train[x_train.columns[j]].sum()
            elif j==0 :
                A[i,j] = x_train[x_train.columns[i]].sum()
            else :
                A[i,j] = (x_train[x_train.columns[i]] * x_train[x_train.columns[j]]).sum()

A

array([[ 160.    , 1118.39  ],
       [1118.39  , 7998.8607]])

In [68]:
for i in range(n):
    if i==0 :
        H[i,0] = y_train[y_train.columns[0]].sum()
    else :
        H[i,0] = (x_train[x_train.columns[i]].values * y_train[y_train.columns[0]].values).sum()

H

array([[ 480.63  ],
       [3460.7775]])

In [69]:
A_list = list()

for j in range(n):
    temp_A = A.copy()
    temp_A[:,j] = H.reshape(n,)
    A_list.append(temp_A)

A_list

[array([[ 480.63  , 1118.39  ],
        [3460.7775, 7998.8607]]),
 array([[ 160.    ,  480.63  ],
        [1118.39  , 3460.7775]])]

In [70]:
b_list = list()

for i in range(n):
    b = np.linalg.det(A_list[i]) / np.linalg.det(A)
    b_list.append(b)

b_list

[-0.8961119222429538, 0.5579519734250787]

In [71]:
print('intercept :',b_list[0])

intercept : -0.8961119222429538


In [72]:
print('coefficients :')
for i in range(1,n):
    print('b'+str(i),':',b_list[i])

coefficients :
b1 : 0.5579519734250787


In [73]:
x_test

cgpa
112  8.58
29   7.15
182  5.88
199  6.22
193  4.57
85   4.79
10   5.32
54   6.86
115  8.35
35   6.87
12   8.94
92   7.90
13   6.93
126  5.91
174  7.32
2    7.82
44   5.09
3    7.42
113  6.94
14   7.73
23   6.19
25   7.28
6    6.73
134  7.20
165  8.21
173  6.75
45   7.87
65   7.60
48   8.63
122  5.12
178  8.15
64   7.36
9    8.31
57   6.60
78   6.59
71   7.47
128  7.93
176  6.29
131  6.37
53   6.47

In [74]:
y_test

package
112     4.10
29      3.49
182     2.08
199     2.33
193     1.94
85      1.48
10      1.86
54      3.09
115     4.21
35      2.87
12      3.65
92      4.00
13      2.89
126     2.60
174     2.99
2       3.25
44      1.86
3       3.67
113     2.37
14      3.42
23      2.48
25      3.65
6       2.60
134     2.83
165     4.08
173     2.56
45      3.58
65      3.81
48      4.09
122     2.01
178     3.63
64      2.92
9       3.51
57      1.94
78      2.21
71      3.34
128     3.34
176     3.23
131     2.01
53      2.61

In [75]:
# y_prediction

y_cap = list()
y_prediction = b_list[0]

for row in x_test.index:
    for i in range(len(x_test.columns)):
        y_prediction = y_prediction + b_list[i+1] * x_test[x_test.columns[i]][row]
    
    y_cap.append(y_prediction)
    y_prediction = b_list[0]

y_cap

[3.891116009744222,
 3.0932446877463593,
 2.384645681496509,
 2.5743493524610357,
 1.653728596309656,
 1.7764780304631733,
 2.072192576378465,
 2.9314386154530863,
 3.7627870558564536,
 2.937018135187337,
 4.09197872017725,
 3.5117086678151685,
 2.9704952535928415,
 2.4013842406992616,
 3.1880965232286225,
 3.4670725099411617,
 1.9438636224906967,
 3.24389172057113,
 2.9760747733270927,
 3.4168568323329054,
 2.557610793258284,
 3.1657784442916195,
 2.858904858907826,
 3.1211422864176135,
 3.684673779576943,
 2.8700638983763276,
 3.494970108612416,
 3.3443230757876443,
 3.9190136084154763,
 1.9606021816934494,
 3.6511966611714377,
 3.2104146021656255,
 3.7404689769194506,
 2.7863711023625655,
 2.7807915826283147,
 3.271789319242384,
 3.5284472270179204,
 2.6134059906007914,
 2.658042148474798,
 2.7138373458173053]

In [76]:
len(y_cap)

40

## Model Evaluation on Test Dataset

In [77]:
y_test

package
112     4.10
29      3.49
182     2.08
199     2.33
193     1.94
85      1.48
10      1.86
54      3.09
115     4.21
35      2.87
12      3.65
92      4.00
13      2.89
126     2.60
174     2.99
2       3.25
44      1.86
3       3.67
113     2.37
14      3.42
23      2.48
25      3.65
6       2.60
134     2.83
165     4.08
173     2.56
45      3.58
65      3.81
48      4.09
122     2.01
178     3.63
64      2.92
9       3.51
57      1.94
78      2.21
71      3.34
128     3.34
176     3.23
131     2.01
53      2.61

In [78]:
# R Square

y_mean = y_test[y_test.columns[0]].mean()

sum1 = 0
sum2 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

for i in y_test.index:
    diff = y_test[y_test.columns[0]][i] - y_mean
    sum2 = sum2 + (diff ** 2)

r2 = 1 - (sum1 / sum2)

print(r2)

0.7807301475103847


In [79]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_cap) # first comes actual value and then predicted value
print(r2)

0.7807301475103846


In [80]:
# MSE

sum1 = 0

for i in range(len(y_cap)):
    diff = y_test.iloc[i][y_test.columns[0]] - y_cap[i] 
    sum1 = sum1 + (diff ** 2)

mse = sum1 / (len(y_cap))
print(mse)

0.12129235313495494


In [81]:
# RMSE

rmse = np.sqrt(mse)
rmse
print(rmse)

0.34827051717731566


In [82]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_cap)
print('MSE :',mse)
rmse = np.sqrt(mse)
print('RMSE :',rmse)

MSE : 0.12129235313495498
RMSE : 0.3482705171773158
